name: "create-and-release-web-apps"
permissions:
  actions: write
  packages: write
  contents: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-ordering:
    uses: ./.github/workflows/create-webapp-artifacts.yml
    with:
        projectfile: 'ordering/ordering.csproj'
        outputfolder: '${{github.env.DOTNET_ROOT}}/ordering'
  build-catalog:
    uses: ./.github/workflows/create-webapp-artifacts.yml
    with:
      projectfile: 'catalog/catalog.csproj'
      outputfolder: '${{github.env.DOTNET_ROOT}}/catalog'
  build-frontend:
    uses: ./.github/workflows/create-webapp-artifacts.yml
    with:
      projectfile: 'frontend/frontend.csproj'
      outputfolder: '${{github.env.DOTNET_ROOT}}/frontend'
  create-release:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with: 
            fetch-depth: 0
        
        - name: Install GitVersion 
          uses: gittools/actions/gitversion/setup@v0.10.2
          with: 
            versionSpec: '5.x'

        - name: Determine Version 
          id: gitversion 
          uses: gittools/actions/gitversion/execute@v0.10.2

        - name: create a relase with version provided by package push
          uses: softprops/action-gh-release@v1
          with:
            token: "${{ secrets.EXTENDED_ACCESSTOKEN }}"
            tag_name: "v${{github.env.GitVersion_SemVer}}"
            generate_release_notes: true
            files: |
                ${{env.DOTNET_ROOT}}/ordering/*
                ${{env.DOTNET_ROOT}}/catalog/*
                ${{env.DOTNET_ROOT}}/frontend/*

